[__config__]
oldver = "cache/oldver.json"
newver = "cache/newver.json"

[github-actions-bin]
source = "github"
github = "actions/runner"
use_latest_release = true

[openfoam]
source = "github"
github = "OpenFOAM/OpenFOAM-10"
use_latest_tag = true

[python-cupy]
source = "github"
github = "cupy/cupy"
use_latest_release = true

[python-librosa]
source = "github"
github = "librosa/librosa"
use_latest_release = true

[python-resampy]
source = "github"
github = "bmcfee/resampy"
use_latest_release = true

[spek]
source = "github"
github = "alexkay/spek"
use_latest_release = true
