[__config__]
oldver = "cache/oldver.json"
newver = "cache/newver.json"

[github-actions-bin]
source = "github"
github = "actions/runner"
use_latest_release = true

[python-librosa]
source = "github"
github = "librosa/librosa"
use_latest_release = true
